name: Npm Release

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write
  actions: read

env:
  cdp-gitbot-email: "147416134+cdp-github-action[bot]@users.noreply.github.com"
  cdp-gitbot-name: "cdp-github-action[bot]"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Get token
        uses: DEFRA/cdp-build-action/get-github-token@stable
        with:
          role_to_assume: arn:aws:iam::094954420758:role/app-config-role
          private_key_id: cdp/platform/gh_apps/DEFRA/cdp-gh-action/private-key
          app_id: 405317
          email: ${{ env.cdp-gitbot-email }}
          username: ${{ env.cdp-gitbot-name }}

      - run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} # https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-nodejs-packages
